apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "testdeploy"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "testdeploy"
    spec:
      containers:
        - name: "testdeploy"
          image: "testdeployaks.azurecr.io/testdeploy"
          ports:
          - containerPort: 3456