apiVersion: v1
kind: Service
metadata:
    name: "testdeploy"
    labels:
        app: "testdeploy"
spec:
    type: LoadBalancer
    ports:
    - port: 3456
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "testdeploy"